var txt = hu;
draw_set_font(fnt_large);
draw_set_halign(fa_right);
draw_set_valign(fa_bottom);
draw_set_color(c_white);
draw_text(240,80,txt);
txt = ha;
draw_set_font(fnt_small);
draw_set_halign(fa_right);
draw_set_valign(fa_bottom);
draw_set_color(c_white);
draw_text(270,140,txt);
